### ISSUE TITLE
Add registration interface to the frontend

### ISSUE THREAD

**Issue by abumalick** [ahlsunnah/learn-islam-ui#243]

**Comment by zerubeus** [comment]
Salam alaykom, I'll be pleased to contribute to this project I'm already working on some similar ideas, so I think it will be nice if we coordinate together

email: zerubeus gmail com

**Comment by abumalick** [comment]
وعليكم السلام ورحمة الله

مرحبا بك

I invited you on slack. please check your mail

**Comment by zerubeus** [comment]
I'm taking this issue inchallah
