### ISSUE TITLE
[Refactor]Replace used components by react components

### ISSUE THREAD

**Issue by abumalick** [ahlsunnah/learn-islam-ui#3]
In the beginning we created most components with the web components of material.io

Now, they have created a nice React integration, it would be cool to use these instead:

https://github.com/material-components/material-components-web-react

- [x] @material/drawer
- [x] @material/radio
- [ ] @material/theme
- [x] @material/toolbar
- [x] @material/typography

**Comment by zerubeus** [comment]
what about @material/theme ?

**Comment by abumalick** [comment]
There is no react component for it:
https://github.com/material-components/material-components-web-react
